services:
  - type: web
    name: app              # ini bebas, bisa ganti sesuai keinginan
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"   # wajib sesuai nama file utama
